apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat11
  labels:
    app: build11
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 4
  selector:
    matchLabels:
      app: build11
  template:
    metadata:
      labels:
        app: build11
    spec:
      containers:
        - name: tomcat1
          image: tomcat:8.5.43-jdk8


