apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: myapp
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes: 
        - name: manual-ebs-01
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          volumeMounts: 
            - name: manual-ebs-01 
              mountPath: "/var/lib/jenkins"
              


