apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: myapp
  ports:
   - name: jenkinsport
     protocol: TCP
     port: 9000
     targetPort: 8080
   - name: hostport2
     protocol: TCP
     port: 50002
     targetPort: 50000
  externalIPs:
    - 172.31.22.159     
