apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: avd
spec:
  limits:
    - default:
        memory: 500Mi
      defaultRequest:
        memory: 250Mi
      type: Container



