apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat1
  labels:
    app: build1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: build1
  template:
    metadata:
      labels:
        app: build1
    spec:
      containers:
        - name: tomcat1
          image: tomcat:8.5.43-jdk8


