apiVersion: v1
kind: Service
metadata:
  name: myservice2
spec:
  type: NodePort
  selector:
    app: myapp3
  ports:
   - name: tomport
     protocol: TCP
     port: 8000
     targetPort: 8080
     nodePort: 30001
   - name: hostport
     protocol: TCP
     port: 50001
     targetPort: 50000
     nodePort: 30002
