apiVersion: v1
kind: Service
metadata:
  name: myservice
spec: 
  selector: 
    app: myapp3
  ports:
   - name: tomport
     protocol: TCP
     port: 8000
     targetPort: 8080
   - name: hostport
     protocol: TCP
     port: 50001
     targetPort: 50000
      

