apiVersion: v1
kind: Service
metadata:
  name: mypod
spec:
  selector:
    app: myapp
  ports:
   - name: jenkins
     protocol: TCP
     port: 8500
     targetPort: 8080
   - name: hostport
     protocol: TCP
     port: 50003
     targetPort: 50000
  externalIPs:
    - 172.31.22.159     
