apiVersion: v1
kind: Service
metadata:
  name: tomcat1
spec:
  selector:
    app: build1
  ports:
   - name: tomport1
     protocol: TCP
     port: 8100
     targetPort: 8080
   - name: tomport2
     protocol: TCP
     port: 51000
     targetPort: 50000
  externalIPs:
    - 172.31.22.159     
